FROM ubuntu:20.04 AS builder
# ARG BASE_IMAGE=nvcr.io/nvidia/l4t-base:r32.4.4
# FROM ${BASE_IMAGE} AS builder
LABEL maintainer="SincLAB-oliverPai"

ENV DEBIAN_FRONTEND noninteractive
RUN  sed -i s@/archive.ubuntu.com/@/mirrors.ustc.edu.cn/@g /etc/apt/sources.list \
      && apt-get clean \
      && apt-get update \
      && apt-get install --no-install-recommends --no-install-suggests -y gnupg2 ca-certificates \
            git build-essential libopencv-dev golang \
      && rm -rf /var/lib/apt/lists/*

# RUN git clone https://github.com/AlexeyAB/darknet.git
COPY darknet darknet
COPY files/yoloTCP_Image.go yoloTCP_Image.go
RUN cd darknet && make \
      && cp darknet /usr/local/bin \
      && cd .. && rm -rf darknet \
      && go build yoloTCP_Image.go && cp yoloTCP_Image /usr/local/bin && rm yoloTCP_Image.go

FROM ubuntu:20.04
# ARG BASE_IMAGE=nvcr.io/nvidia/l4t-base:r32.4.4
# FROM ${BASE_IMAGE}

LABEL maintainer="SincLAB-oliverPai"

ENV DEBIAN_FRONTEND noninteractive

RUN sed -i s@/archive.ubuntu.com/@/mirrors.ustc.edu.cn/@g /etc/apt/sources.list \
      && apt-get clean \
      && apt-get update \
      && apt-get install --no-install-recommends --no-install-suggests -y libopencv-highgui-dev\
      && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/bin/darknet /home
COPY --from=builder /usr/local/bin/yoloTCP_Image /home
COPY files /home
WORKDIR /home
ENTRYPOINT ./yoloTCP_Image

